# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0002_rezervacija'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letnik',
            options={'ordering': ('oddelek', 'smer', 'leto'), 'verbose_name_plural': 'letniki'},
        ),
        migrations.AddField(
            model_name='letnik',
            name='oddelek',
            field=models.CharField(blank=True, choices=[('M', 'matematika'), ('F', 'fizika')], max_length=1),
        ),
        migrations.AlterField(
            model_name='letnik',
            name='leto',
            field=models.CharField(max_length=192, null=True),
        ),
    ]
