# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0003_auto_20170901_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='srecanje',
            options={'ordering': ('predmet', 'tip', 'oznaka', 'ucitelj', 'dan', 'ura', 'trajanje'), 'verbose_name_plural': 'srečanja'},
        ),
    ]
