# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0003_auto_20170920_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='letnik',
            name='kratica',
            field=models.CharField(default='???', max_length=64),
            preserve_default=False,
        ),
    ]
