# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


def nastavi_ucitelje(apps, schema_editor):
    Srecanje = apps.get_model('urnik', 'Srecanje')
    for srecanje in Srecanje.objects.all():
        if srecanje.ucitelj:
            srecanje.ucitelji.add(srecanje.ucitelj)

class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0004_letnik_kratica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='srecanje',
            options={'ordering': ('predmet', 'tip', 'oznaka', 'dan', 'ura', 'trajanje'), 'verbose_name_plural': 'srečanja'},
        ),
        migrations.AddField(
            model_name='srecanje',
            name='ucitelji',
            field=models.ManyToManyField(blank=True, related_name='srecanja', to='urnik.Oseba'),
        ),
        migrations.RunPython(
            code=nastavi_ucitelje
        ),
        migrations.RemoveField(
            model_name='srecanje',
            name='ucitelj',
        ),
    ]
