# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0005_vec_uciteljev'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='dan',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='do_ura',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='od_ura',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
