# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0006_novi_termini_rezervacij'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervacija',
            name='do',
        ),
        migrations.RemoveField(
            model_name='rezervacija',
            name='od',
        ),
        migrations.RenameField(
            model_name='rezervacija',
            old_name='do_ura',
            new_name='do',
        ),
        migrations.RenameField(
            model_name='rezervacija',
            old_name='od_ura',
            new_name='od',
        ),
    ]
