# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0007_odstrani_stare_termine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezervacija',
            options={'ordering': ('dan', 'od', 'do'), 'verbose_name_plural': 'rezervacije'},
        ),
    ]
