# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0011_semester_objavljen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='opomba',
            field=models.CharField(max_length=192),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='osebe',
            field=models.ManyToManyField(related_name='rezervacije', to='urnik.Oseba'),
        ),
    ]
