# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0012_obvezna_polja_rezervacij'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='dan_konca',
            field=models.DateField(blank=True, help_text='Izpolni le, če je drugačen od začetka', null=True, verbose_name='Dan konca'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='dan',
            field=models.DateField(verbose_name='Dan začetka'),
        ),
    ]
