# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urnik', '0012_obvezna_polja_rezervacij'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
