# Generated by Django 2.0.9 on 2019-02-13 18:46

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    # We can't import the User model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('auth', 'User')
    try: default = User.objects.earliest('pk')
    except User.DoesNotExist:
        default = User.objects.create(
            username='migraton', email='migration',
            password=make_password('migration')
        )
        default.is_active = False
        default.save()
    try: mat = User.objects.get(username='vardjan')
    except: mat = default

    try: fiz = User.objects.get(username='anzicek')
    except: fiz = default

    Rezervacija = apps.get_model('urnik', 'Rezervacija')
    for r in Rezervacija.objects.all():
        if any(u.tip in "MR" for u in r.ucilnice.all()):
            r.avtor_rezervacije = mat
        elif any(u.tip in "FP" for u in r.ucilnice.all()):
            r.avtor_rezervacije = fiz
        else:
            r.avtor_rezervacije = default
        r.save()
    pass


def backward(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urnik', '0014_auto_20190131_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='avtor_rezervacije',
            field=models.ForeignKey(null=True, help_text='Kdo je dejansko naredil rezervacijo.', on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='osebe',
            field=models.ManyToManyField(help_text='Osebe, ki si lastijo to rezervacijo.', related_name='rezervacije', to='urnik.Oseba', verbose_name='Osebe'),
        ),
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='rezervacija',
            name='avtor_rezervacije',
            field=models.ForeignKey(null=False, help_text='Kdo je dejansko naredil rezervacijo.', on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to=settings.AUTH_USER_MODEL),
        ),
    ]
