# Generated by Django 2.0.9 on 2019-02-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urnik', '0015_auto_20190213_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='oseba',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oseba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='avtor_rezervacije',
            field=models.ForeignKey(help_text='Kdo je dejansko naredil rezervacijo', on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='cas_rezervacije',
            field=models.DateTimeField(auto_now_add=True, help_text='Datum in čas, ko je bila rezervacija narejena', verbose_name='Datum in čas rezervacije'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='dan',
            field=models.DateField(help_text='Za kateri dan želite rezervirati', verbose_name='Dan začetka'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='dan_konca',
            field=models.DateField(blank=True, help_text='Dan konca rezervacije; izpolnite le, če je drugačen od začetka', null=True, verbose_name='Dan konca'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='do',
            field=models.PositiveSmallIntegerField(choices=[(7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], help_text='Do katere ure želite rezervirati'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='od',
            field=models.PositiveSmallIntegerField(choices=[(7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], help_text='Od katere ure želite rezervirati'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='opomba',
            field=models.CharField(help_text='Razlog za rezervacijo', max_length=192),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='osebe',
            field=models.ManyToManyField(help_text='Osebe, ki si lastijo to rezervacijo', related_name='rezervacije', to='urnik.Oseba', verbose_name='Osebe'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='potrjena',
            field=models.BooleanField(default=False, help_text='Ali so to rezervacijo potrdili posvečeni ljudje'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='ucilnice',
            field=models.ManyToManyField(help_text='Izberite učilnice, ki jih želite rezervirati', limit_choices_to={'tip__in': ('M', 'F', 'R', 'P')}, related_name='rezervacije', to='urnik.Ucilnica', verbose_name='Učilnice'),
        ),
    ]
