# Generated by Django 2.0.9 on 2019-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0016_auto_20190225_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='osebe',
            field=models.ManyToManyField(related_name='rezervacije', to='urnik.Oseba', verbose_name='Osebe'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='ucilnice',
            field=models.ManyToManyField(limit_choices_to={'tip__in': ('M', 'F', 'R', 'P')}, related_name='rezervacije', to='urnik.Ucilnica', verbose_name='Učilnice'),
        ),
    ]
