# Generated by Django 2.2.10 on 2020-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0017_auto_20190925_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letnik',
            options={'default_related_name': 'letniki', 'ordering': ('oddelek', 'smer', 'leto'), 'verbose_name_plural': 'letniki'},
        ),
        migrations.AlterModelOptions(
            name='rezervacija',
            options={'default_related_name': 'rezervacije', 'ordering': ('dan', 'od', 'do'), 'verbose_name_plural': 'rezervacije'},
        ),
        migrations.AlterModelOptions(
            name='srecanje',
            options={'default_related_name': 'srecanja', 'ordering': ('predmet', 'tip', 'oznaka', 'dan', 'ura', 'trajanje'), 'verbose_name_plural': 'srečanja'},
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='predmeti',
            field=models.ManyToManyField(blank=True, related_name='rezervacije', to='urnik.Predmet'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='opomba',
            field=models.CharField(help_text='Razlog za rezervacijo, če je rezervacija povezana s predmetom, spodaj nastavite tudi predmet.', max_length=192),
        ),
    ]
