# Generated by Django 2.2.13 on 2020-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0018_auto_20200306_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucilnica',
            name='korona_velikost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
