# Generated by Django 2.2.13 on 2020-10-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0019_ucilnica_korona_velikost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucilnica',
            name='dovoli_veckratno_rezervacijo',
            field=models.BooleanField(default=False),
        ),
    ]
